# Generated by Django 4.1.2 on 2022-12-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('square_ft', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('garage_spaces', models.IntegerField(default=0)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('lot_size', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(default=0)),
                ('days_listed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Home Data',
            },
        ),
    ]
